name: Build project

on: 
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  # testProject:
  #   uses: ./.github/workflows/testProject.yml
  #   secrets:
  #   UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #   UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  #   UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  #  new
  discordMessage_ProcessStarted:
    uses: ./.github/workflows/discordMessage.yml
    with:
      message: "A new game build ${{ github.ref_name }} for ${{ github.repository }} is being processed! Stay tuned for updates on GitHub Releases and Itch.io!  You can view the workflow [here](${{ github.server_url }}/${{ github.repository }}/actions/run/${{github.run_id}})"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  buildForAllSupportedPlatforms:
    # needs: testProject
    uses: ./.github/workflows/buildForAllPlatforms.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  deployToItch:
    needs: buildForAllSupportedPlatforms
    uses: ./.github/workflows/deployToItch.yml
    with:
      run_id: ${{ github.run_id }}
    secrets:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      ITCH_USERNAME: ${{ secrets.ITCH_USERNAME }}
      ITCH_GAME_ID: ${{ secrets.ITCH_GAME_ID }}
  deployToGitHubRelease:
    needs: buildForAllSupportedPlatforms
    uses: ./.github/workflows/deployToGitHubRelease.yml
    with:
      run_id: ${{ github.run_id }}
      artifactName: Build-WebGL
      zipName: ${{ github.ref_name }}_Itch_WebGL_FullGame.zip
      tagName: ${{ github.ref_name }}
      note: "${{ github.event.head_commit.message }}"
      prerelease: true
  discordMessage_ProcessFinished:
    needs: [deployToGitHubRelease, deployToItch]
    # needs: deployToItch
    uses: ./.github/workflows/discordMessage.yml
    with:
      message: "A new game build ${{ github.ref_name }} for ${{ github.repository }} has been deployed to [GitHub Releases](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}) and [Itch.io](${{ vars.ITCH_URL }})! Check it out! "
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      # new