name: Build For All Platforms
on:
  workflow_call:
    secrets:
      UNITY_LICENSE:
        required: true
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true
  workflow_dispatch:

jobs:
  buildForAllSupportedPlatforms:
      name: Build for ${{ matrix.targetPlatform }}
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          buildPair:
            - {buildName: Itch_Web_Game, targetPlatform: WebGL, buildProfile: 'Assets/Settings/Build Profiles/Itch_Web_Game.asset'}
            - {buildName: Itch_Win_Game, targetPlatform: Windows, buildProfile: 'Assets/Settings/Build Profiles/Itch_Win_Game.asset'}
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            lfs: true
        - uses: actions/cache@v3
          with:
            path: Library
            key: Library-${{ matrix.buildPair.buildName }}
            restore-keys: Library-
        - if: matrix.buildPair.targetPlatform == 'Android'
          uses: jlumbroso/free-disk-space@v1.3.1
        - uses: game-ci/unity-builder@v4
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            targetPlatform: ${{ matrix.buildPair.targetPlatform }}
            buildProfile: ${{ matrix.buildPair.buildProfile }}
        - uses: actions/upload-artifact@v7
          with:
            name: Build-${{ matrix.buildPair.buildName }}
            path: build/${{ matrix.buildPair.buildName }}
