name: Deploy to Itch.io
on:
  workflow_call:
    inputs:
      run_id:
        description: 'The id of the workflow we want to download the artifact from'
        required: true
        type: string
    secrets:
      BUTLER_API_KEY:
        required: true
      ITCH_USERNAME:
        required: true
      ITCH_GAME_ID:
        required: true

  workflow_dispatch:
    inputs:
      run_id:
        description: 'The id of the workflow we want to download the artifact from'
        required: true
        type: string



jobs:
  deploy:
    name: Deploy - Itch.io ${{ matrix.buildPair.channel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildPair:
            - {buildName: Itch_Web_Game, channel: WebGL}
            - {buildName: Itch_Win_Game, channel: Windows}
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: Build-${{ matrix.buildPair.buildName }}
          path: build/${{ matrix.buildPair.buildName }}
          run-id: ${{ inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/${{ matrix.buildPair.buildName }}
          itchUsername: ${{secrets.ITCH_USERNAME}}
          itchGameId: ${{ secrets.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.buildPair.channel }}
